#!/usr/bin/env bash

# secret.pdf -> pdf is suffix (file extentions)

file=secret.projectX.pdf

# starts from beginning go to 1st . and removes everything before
echo "${file#*.}"
# greedy (2 hashes ##)
echo "${file##*.}"

# start from end
echo "${file%.*}"
echo "${file%%e*}"


# environment variable
echo "$PWD"

repo_path="${PWD%/*}"
echo "$repo_path"

repo_name="${repo_path##*/}"
echo "$repo_name"
