#!/usr/bin/env bash

greeter(){
    echo "Hello ${1^}, you are $2 years old"
}

# call function greeter with args bob and 15 (we pre-determin what will be written inside the script itself)
greeter bob 15

# takes in argument from calling script (we give it the infromation outside the script)
greeter $1 $2
